apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-helm
  labels:
    {{- include "random-shapes.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "random-shapes.selectorLabels" . | nindent 4 }}
