apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-color-app
spec:
  selector:
    matchLabels:
      app: php-color-app
  replicas: 1
  template:
    metadata:
      labels:
        app: php-color-app
    spec:
      containers:
      - name: php-color-app
        image: siddharth67/php-color:v1
        env:
        - name: COLOR
          valueFrom:
            configMapKeyRef:
              name: php-color-cm
              key: circle-color
