apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-shapes
spec:
  selector:
    matchLabels:
      app: random-shapes
  replicas: 1
  template:
    metadata:
      labels:
        app: random-shapes
    spec:
      containers:
      - name: random-shapes
        image: siddharth67/php-random-shapes:v1
        env:
        - name: COLOR
          valueFrom:
            configMapKeyRef:
              name: php-color-cm
              key: circleColor
